- name: import task1
  ansible.builtin.import_tasks: greeting.yml
  vars:
    name: sandeep

- name: import task2
  ansible.builtin.import_tasks: greeting.yml
  vars:
    name: madhu

- name: include task
  ansible.builtin.include_tasks: "{{ file }}.yml"
  vars:
    file: greeting
    name: amma

- name: import a role statically
  ansible.builtin.import_role:
    name: demo-0

- name: import a role statically but another task
  ansible.builtin.import_role:
    name: demo-0
    tasks_from: greet

- name: import a role dynamically
  ansible.builtin.include_role:
    name: demo-0

- name: import a role statically but another task
  ansible.builtin.include_role:
    name: demo-0
    tasks_from: greet